# Generated by Django 3.2 on 2021-08-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficpolice',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_location', to='EVSCapp.trafficpolicelocation'),
        ),
    ]
