# Generated by Django 3.2 on 2021-08-08 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0002_trafficpolice_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficpolice',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='report',
            name='traffic_police',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EVSCapp.trafficpolice'),
        ),
    ]
