# Generated by Django 3.2 on 2021-08-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0003_auto_20210808_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_plate',
            field=models.CharField(max_length=11),
        ),
    ]
