# Generated by Django 3.2.6 on 2021-08-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0004_alter_vehicle_vehicle_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemadmin',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
