# Generated by Django 3.2.6 on 2021-08-22 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0009_alter_notification_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='EVSCapp.records'),
        ),
        migrations.AlterField(
            model_name='report',
            name='traffic_police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVSCapp.trafficpolice'),
        ),
    ]
