# Generated by Django 3.2.6 on 2021-08-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0010_auto_20210822_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_chewing_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_drunk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_not_having_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='is_using_cell_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='other_violation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='payment_amount',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='short_summary',
            field=models.TextField(null=True),
        ),
    ]
