# Generated by Django 3.2.6 on 2021-08-24 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0012_auto_20210823_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='address',
        ),
    ]
