# Generated by Django 3.2.6 on 2021-08-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0013_remove_records_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='vehicle_speed',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
