# Generated by Django 3.2.6 on 2021-09-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVSCapp', '0016_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
